### ISSUE TITLE
Track Definition is incomplete

### ISSUE THREAD

**Issue by suhasHere** [kixelated/warp-draft#101]
Currently track is defined to have init segment , which might not be true for all the use-cases
Also track Ids are undefined and in order to support multi-host distribution systems , we need to describe how tracks from multiple tenants are differentiated within and across distribution networks.

**Comment by vasilvv** [comment]
> Currently track is defined to have init segment , which might not be true for all the use-cases

I don't believe this is true.  Almost all encodings require some form of prior knowledge in order to decode their bitstream (e.g. even something as simple as a raw PCM audio requires knowing a sampling rate and the number of channels).

> Also track Ids are undefined and in order to support multi-host distribution systems , we need to describe how tracks from multiple tenants are differentiated within and across distribution networks.

Could you elaborate on the scenario you have in mind here?  Currently, the track IDs are scoped to a track bundle.  If the application needs to combine tracks from multiple bundles, it currently has two options:
1. Solve the problem entirely at the application layer: have the application receive the list of bundles it needs to separately, and then subscribe to them individually.
2. Recombine multiple track bundles into a single bundle somewhere in the distribution chain.  This is tricky since this technically requires the bundler to alter the catalog, but we assume the catalog is generally opaque and can be encrypted.

**Comment by suhasHere** [comment]
> I don't believe this is true. Almost all encodings require some form of prior knowledge in order to decode their bitstream (e.g. even something as simple as a raw PCM audio requires knowing a sampling rate and the number of channels).
> 
> >

This is what is in the current draft -
"A media track in Warp is a combination of an init object and a sequence of media object groups." 
I don't see the need to define there needs to be an init object. Since i don't anywhere "Init Object" being defined.  OTOH, the sample rate, number of channels seems to be part of manifest/catalog/ or something that goes in SDP for example

**Comment by suhasHere** [comment]
> Could you elaborate on the scenario you have in mind here? Currently, the track IDs are scoped to a track bundle.

First thing, is no "track bundle" doens't say that today and I feel a bundle shouldn't scope the naming of the track. A track bundle, atleast as it is defined in -04, is group of tracks that share certain properites. A bundle can have tracks from multiple emitters. Its application's choice.

If the properties of trackIds are undefined,  then more than one publisher from different applications and domains can create tracks with name "audio"  and when an Object with trackId "audio" traverses through the Relays within a distribution network and across distribution networks , there is no much information to decide on what audio means ..

**Comment by afrind** [comment]
> IIUC the draft-04 on "track bundle" doens't say that today and I feel a bundle shouldn't scope or define the naming of the track.

@suhasHere is correct, the current language says only that a track ID needs to be unique within the track-bundle.  They can also be *more* unique than that, globally even as 62 bits will allow.  

It seems like the question is "should they be required to be globally unique?"

**Comment by kixelated** [comment]
The contents of the init payload depends on the format. If there's no initialization payload required, then just send 0 bytes.

And yeah, I agree with @afrind verbatim.

**Comment by kixelated** [comment]
Although I will add that we should switch track ID from a varint to a variable length bytes.

**Comment by fluffy** [comment]
Seems to be a bunch things mixed together in this one. Might be better to split into multiple issues. 

1 issue seems to be we need a globally unique track name of some sort.  (I think that is seperate from the TrackID that might be a short integer that is unque only the the quic connection and gives us a short reference to the longer global name. 

2 issue has to do with init sequence. I think I was thinking that for say an simple PCM audio track, the catalog would say the sample rate and sample size. But Victors comment that no this could be the init might be the right way to think about it. I can see how that would work and not clear to me which is best. I hope that gets explored in the content / format / catalog drafts.

**Comment by afrind** [comment]
Has #121, plus the discussion to move INIT into media formats resolved the discussion in this issue?

**Comment by afrind** [comment]
Track definition has been updated.
