### ISSUE TITLE
Stabilizing the handshake format

### ISSUE THREAD

**Issue by vasilvv** [kixelated/warp-draft#107]
If we are going to ship experimental versions of MoQ (which we should), those probably should be interoperable on a handshake level (meaning that a server can accept two clients speaking different iterations of MoQ).  We currently have the following format in the draft:

```
SETUP Parameter {
  Parameter Key (i),
  Parameter Value Length (i),
  Parameter Value (..),
}

Client SETUP Message Payload {
  Number of Supported Versions (i),
  Supported Version (i) ...,
  SETUP Parameters (..) ...,
}

Server SETUP Message Payload {
  Selected Version (i),
  SETUP Parameters (..) ...,
}
```

Astute reader will notice that this negotiation mechanism is similar to [a certain other IETF protocol](https://tlswg.org/tls13-spec/draft-ietf-tls-rfc8446bis.html#name-supported-versions).

The question I want to explicitly ask here is: are we okay with this format?  We obviously can change it later down the line, but that would be tricky since we'd create an incompatibility (and we also don't have the Alt-Svc escape hatch that QUIC used).

**Comment by fluffy** [comment]
Seems like a down the road issue, but sure , this would work to for now and we can make sure we  rethink it as we get closer to done. I had assumed we would have a MoQ ALPN too. Would that be part of this ?

**Comment by afrind** [comment]
>  we would have a MoQ ALPN too.

This doesn't work for the WebTransport case, which will use "h3" ALPN.  Perhaps there could be the ALPN equivalent in the CONNECT headers?

**Comment by vasilvv** [comment]
> Seems like a down the road issue, but sure , this would work to for now and we can make sure we rethink it as we get closer to done. I had assumed we would have a MoQ ALPN too. Would that be part of this ?

No, I was mostly concerned about this for MoQ over WebTransport.  For MoQ over raw QUIC, it's actually entirely possible to just use ALPN for version negotiation (which is what H/3 does).

----------

I am closing this, since it appears we did have a very rough agreement at 116 (or at least no one seemed to object).
