### ISSUE TITLE
Support track as independent component of the data model

### ISSUE THREAD

**Issue by suhasHere** [kixelated/warp-draft#109]
MoQ should focus on delivering tracks and conceptual grouping of tracks can be built atop of it. 

This would need
- Track Ids to be fully specified within on Subscribe and Publish Requests
- Allows tracks to specify authorization scope for its namespace.
- Control Streams/Messages mapped to Subscribe/Publish of tracks
- Allow tracks to grouped for identification or other purposes in application specified way

The transport should provide necessary tools to help support different applications requirements.

**Comment by afrind** [comment]
As an individual:

> might not need information at the session level.

Can you clarify what you think is the missing information?  All that's specified now is the endpoint you are connecting to.  You already need the hostname and the port just to make the QUIC connection so all that we're talking about is a path, or is there more?  Is it authentication information?

>  it feels like an application choice to decide what and how to bundle or not

I agree, but as I read it there's very little difference between "no bundle" and "one bundle with all the tracks".  How do you see these two options as different?  I think it might be simpler to have a single model (bundle/track/group/object) rather than having optional layers.

> Allowing track identifiers to be self contained, shall enable uniform protocol operation within and across distribution networks.

I'm ok with track identifiers that are self contained.  The object model Luke presented today only said that tracks need to be unique within a bundle, it didn't say they couldn't be *more* unique than that.  So perhaps we're close to agreement here?  I think we'll need a transport-scoped identifier to refer to a track that is not globally unique, but that's basically a compression scheme that we can work out later.

I can envision a world where a bundles are named by URLs and when a track is named by a URL that shares a prefix with the enclosing bundle you can subscribe to it with a relative rather than absolute ID.  Again -- it's an optimization we can work out later.

**Comment by suhasHere** [comment]
@afrind I did update the issue to reflect the requirements/discussions from the slides presented today.

**Comment by afrind** [comment]
Thanks @suhasHere.

As an individual:

First, at a high level, I've come to agree that tracks should be the top level component of the *object model*, in as much as we think about the object model as end-to-end, and cacheable.  We've stated a requirement to split and merge tracks from different bundles so they seem more ephemeral to me.  I think some applications might use bundles end-to-end but it doesn't have to be a requirement.

Taking these one by one:

> Track Ids to be fully specified within on Subscribe and Publish Requests

I am OK with this. 

> Allows tracks to specify authorization scope for its namespace.

I'm not sure I understand this one, do you mean something like a track ID can have a domain?

> Control Streams/Messages mapped to Subscribe/Publish of tracks

I agree the draft does need some refinement of how control streams and messages work, but I'm sure how it relates to this issue (track independence).  Can you clarify how they are coupled or can we move that to a separate issue?

> Allow tracks to grouped for identification or other purposes in application specified way

The draft already allows for grouping of tracks in an application specified way (bundles).  I think you are asking for a decoupling of the bundle identifier and the track identifier?  If that's the ask I'm ok with it.

**Comment by suhasHere** [comment]
> > Allows tracks to specify authorization scope for its namespace.

I will try to steal the name that Mo suggested for a bit
Track Prefix = provider reference (https://acme.tv/session123). This is what you get from Catalog or the one in connect url when using WT session. 

Track Suffix = small string that you append to the prefix to get the full track name. Example would be "audio"

Track Name = Track Prefix + Track Suffix  ( https://acme.tv/session123/audio)

Track Id = a varint identifier that goes in every object header

The subscribe and publish requests carry the TrackName.  I understand it is some duplication of bytes when using WT, but given its a control message that is not a concern. This will let the subscribe work with fully specified track names and every hop knows what to do with it and it is uniform across distribution networks. 

We can have some caveats that mentions what to do if the track prefix of the track name know from a different context.  


I like to start from small building blocks and build larger things out of it. This will keep the protocol work across multiple use-cases and transport usages.

**Comment by suhasHere** [comment]
> > Allows tracks to specify authorization scope for its namespace.

I will try to steal the name that Mo suggested for a bit
Track Prefix = provider reference (https://acme.tv/session123). This is what you get from Catalog or the one in connect url when using WT session.

Track Suffix = small string that you append to the prefix to get the full track name. Example would be "audio"

Track Name = Track Prefix + Track Suffix ( https://acme.tv/session123/audio)

Track Id = a varint identifier that goes in every object header

The subscribe and publish requests carry the TrackName. I understand it is some duplication of bytes when using WT, but given its a control message that is not a concern. This will let the subscribe work with fully specified track names and every hop knows what to do with it and it is uniform across distribution networks.

We can have some caveats that mentions what to do if the track prefix of the track name know from a different context.

I like to start from small building blocks and build larger things out of it. This will keep the protocol work across multiple use-cases and transport usages.

More details here on the ML (https://mailarchive.ietf.org/arch/msg/moq/20trhc_UsLnupHDcf2eeZb2we3E/)

**Comment by vasilvv** [comment]
> The subscribe and publish requests carry the TrackName.

What happens if I connect to `https://example.org/stream`, and request a track that belong to, say, `https://acme.tv/stream` instead of example.org?

**Comment by fluffy** [comment]
We need to agree on the series of names and sub names and where they are in the protocol to get to unique name for the object. The relays have to have some way to keep track of what goes where when multiple applications use the same relay. 

I don't care much about what the exact hierarchy is as long as it is clear.  It sounded to me like it was turning into roughly something along lines of 

some name for Application URL (note might not the same as connect URL ) 
-> priority domain 
   -> trackID
      ->  GroupID
         -> ObjectID

**Comment by kixelated** [comment]
In my opinion, this clashes with #117.

If track is the top level in the object model, then it's undefined how tracks are clustered. A relay needs some way of knowing what tracks are pooled together, either to create multiple QUIC connections, or sessions within a QUIC connection.

How does a relay learn this grouping?

**Comment by fluffy** [comment]
I'd like to see a design sketched out where each track has a priorityDomain property.  Each track is in exactly 1 priortyDomain. Then describe how a any devices that sends tracks uses the priorityDomain to decide how the object gets mapped onto the underlying transport.

**Comment by fluffy** [comment]
On the topic of if a track can be in multiple priroties domains, I don't see how that would work. We are going to want to say "if object A and B are in same priority domain, send in same bundle".

If a track A was in in two priority domains 1 and 2, and track B was in priority domains 2 and 3. And track C was just in 3. I no longer see how we construct what bundle to use for each track. It seems like a track needs to be in exactly one

**Comment by kixelated** [comment]
I want to step back here a bit more. What is the use-case?

From what I can piece together, it sounds like the use-case is sharing content between broadcasts. In Yokohama, Cullen briefly mentioned two WebEx conferences sharing the same Youtube video. The goal is to share a cache within the CDN.

Ted also mentioned on the mailing list an example where two sports broadcasters receive and publish the exact same stadium feed. Again the goal is to share a cache within the CDN.

Is there anything I'm missing?


In both cases, this would be implementing by subscribing to track URLs with dramatically different prefixes. In the conferencing case, the CDN would primarily serve tracks from a webex.com domain while (somehow) it would serve tracks from a youtube.com domain over the same connection.

**Comment by afrind** [comment]
The use case as I understand it has more to do with relays that are mixing and matching tracks from different "broadcasts".  Eg in a conference there are N participants each "broadcasting" M different tracks and a relay may be selecting subgroups of the tracks for each viewer of the conference.  In this way, the track may not be bound to the broadcast it originated in as far as the data-model goes.

**Comment by afrind** [comment]
Can this be closed now that #121 has merged, or are we waiting to remove bundle entirely?

**Comment by afrind** [comment]
Tracks are now an independent component of the data model, possibly pending some cleanup of text related to bundles.
