### ISSUE TITLE
Relay behavior needs to be specified

### ISSUE THREAD

**Issue by suhasHere** [kixelated/warp-draft#112]
Current spec lacks relays interaction within the protocol. It is very hard for a relay implementor to get an idea on how to build a useful relay. 

We need to specify behavior on
- how to use tracks to identify the origin 
- describe policy enforcement behavior
- describe how to provide appropriate congestion response 
- non-normatively describe implications of protocol design options (bundles/tracks)
- may be some more

We need to have some basic information captured in the base transport.

**Comment by suhasHere** [comment]
PRs #67 #95  has some aspects of it. They may need some cleanup,  but it would be good to get to next steps on getting relays behavior specified in the base transport.

**Comment by vasilvv** [comment]
I think I've stated my position before, but I don't remember which issue or PR it was, so I will restate it now.

As a general principle, the protocol should behave the same (or as close as possible) regardless of whether a receiver is subscribing to a relay or to the publisher directly.  Similarly, the encoder should behave the same regardless of whether it is publishing to a relay or to a receiver directly.

In the light of the principle above, how much of the text in those PRs is actually necessary, or needs to be generalized to include non-relays?

**Comment by fluffy** [comment]
I agree with Victor that mostly is the same as point to point but I think you still have to specify quite a bit about what happen with things like priority when you are transferring things from multiple incoming connections to multiple outgoing connections.

**Comment by kixelated** [comment]
Yeah, the issue seems to be that there's no enough editorial text. We should add some for sure but I agree with Victor; this draft should focus on the hop-to-hop transport.

**Comment by fluffy** [comment]
No we agreed to make relays part of this WG. We need to adopt a draft that aligned with the architecture and requirements in the charter.

**Comment by kixelated** [comment]
> No we agreed to make relays part of this WG. We need to adopt a draft that aligned with the architecture and requirements in the charter.

Sorry, to clarify the transport MUST be designed to support relays. We should make sure that all of the functionality needed by a relay is addressed (separate issues please).

**Comment by vasilvv** [comment]
> I agree that most things are the same but there are many things that you can't just add in later with relays if you don't have them form the start.

I agree, but I assume we would treat those things as individual issues.  What I am trying to understand is: what are the specific changes requested in this particular issue?

**Comment by vasilvv** [comment]
To clarify what I am trying to say here.  I am trying to separate "MoQ design requirements that arise from supporting relays" and "text specific to how relays work"; we definitely need to address the former, but I am not sure how much of the latter we actually need.

**Comment by kixelated** [comment]
I enumerated some specific CDN/relay specific use-cases and requirements in: #117 #118 #119 #120. I think I got the important ones, but you should probably some more. I've spent a long time working on CDNs so hopefully it's helpful?

I agree with Victor. I think we should have a normative transport draft and at least a non-normative scenarios/requirements/use-cases draft. Of course the transport draft MUST support relay use-cases, but for example it shouldn't elaborate on how CDNs are typically architected. The issues I filed should really go into that use-cases draft.

**Comment by afrind** [comment]
@suhasHere Did #126 and #127 resolve this issue?  if not maybe close this and open a more specific one?

**Comment by afrind** [comment]
Closing this for now based on above PRs.  You can reopen or open a new issue to track additional relay requirements.
