### ISSUE TITLE
Move the streaming format description outside the base spec

### ISSUE THREAD

**Issue by suhasHere** [kixelated/warp-draft#113]
This is reflecting the discussions on having a separate spec describe the streaming format (cmaf, webcodecs based format)

**Comment by fluffy** [comment]
+1 on doing this.

**Comment by kixelated** [comment]
I'm going to work on splitting the warp draft into a transport only section. Will started the media half here: https://github.com/wilaw/MoQ

I want these to be in the same GitHub repo eventually. Should we do that now or wait for adoption?

**Comment by afrind** [comment]
See also #66, maybe one of these can be closed as a duplicate?

**Comment by afrind** [comment]
Duplicate of #66 and related to #146
