### ISSUE TITLE
Native QUIC and WT support

### ISSUE THREAD

**Issue by suhasHere** [kixelated/warp-draft#114]
@vasilvv has agreed to write a starter PR on this. I am documenting the issue for tracking purposes.

Thanks @vasilvv

**Comment by fluffy** [comment]
I hoping to see a raw quic Connect message that has about the same semantic content of the part of the HTTP connect we are using and something that deals with error code that is sent when a web transport is terminated. As far as I can tell, the rest of the protocol should be the same between the two.

**Comment by vasilvv** [comment]
Fixed via #135.
