### ISSUE TITLE
Catalog needs to describe track details further

### ISSUE THREAD

**Issue by suhasHere** [kixelated/warp-draft#115]
Catalog spec should provide track and media info 

Provide track identifier information

Minimal Media info on the lines of bitrate, samplerate, codec name, resolution and similar quality information per track.

Details to identify the Container format.

Will Law has agree to work on expanding the catalog spec. Documenting the issue here, until we decide a right home for it.

**Comment by acbegen** [comment]
Why reinvent the wheel? Have a look at what DASH MPD provides and do more or less what it does :)

**Comment by fluffy** [comment]
Ali - can you point us at the right thing to be reading or referring to for dash mpd. I want to get my head around if it would work the audio conferencing type use cases. I'm also assuming we will have multiple types of catalogs and this could be one of them.

**Comment by kixelated** [comment]
Yeah, there's already a ton of existing "catalog formats" out there. For example: SDP, M3U8, DASH, MP4 (moov), etc.

I don't think we should define our own until we full understand the problems with these existing standards.

**Comment by afrind** [comment]
Based on agreement at 116 to move this out of base protocol, do you want to move this issue to the https://github.com/wilaw/MoQ repo?

**Comment by afrind** [comment]
I'm closing this issue - please open one against the wilaw/MoQ repo if doesn't meet your requirements.
