### ISSUE TITLE
PLAY message

### ISSUE THREAD

**Issue by kixelated** [kixelated/warp-draft#13]
Currently, there's no way to determine which layers/tracks get pushed. We probably need a new message to control which tracks the consumer wants. We need to support both simulcast (send all tracks), ABR (send one track of this group), and manual track selection (send just these tracks).

**Comment by vasilvv** [comment]
I assume this should be the part of a higher-layer protocol / an optional extension, rather than the push layer.  I am not sure this makes sense for, e.g., the ingestion use case.

**Comment by kixelated** [comment]
A few features are still missing but this is SUBSCRIBE
