### ISSUE TITLE
Changes to moq-transport draft to make it compatible with separate media draft(s)

### ISSUE THREAD

**Issue by wilaw** [kixelated/warp-draft#146]
This issue tracks changes necessary in https://github.com/kixelated/warp-draft/ in order to turn it in to definition of a generic transport that is compatible with external media draft(s). Changes are listed per section of https://kixelated.github.io/warp-draft/draft-lcurley-warp.html per commit [c57d17c] on April 22nd.

**Abstract**
Update text to remove reference to "media" and instead describe moq-transport as a generic transport for moving tracks of objects.

**1. Introduction**
Update language to remove media, and update section definitions as appropriate.

**1.1 Terms and definitions**
Remove definitions for codec, container, decoder, decode timestamp, encoder,frame, i-frame, group of pictures, group of samples, presentation timestamp, variant. To save effort, these definitions can be copied over to the relevant media format spec(s). 

**2.1 Objects**
Remove references to "media objects". The model should be completely agnostic to the payload. 

**2.2 Groups**
Redefine to be non media dependent.

**2.3 track**
Redefine to be non media dependent.
Perhaps give a non media example in additional to the existing media example. 

**2.5 Example**
Remove - this example is relevant in the media format spec. 

**3 Motivation**
IMO this whole section can be removed. It is not necessary when defining a protocol to describe the background motivation for doing so. This could be relegated to an informative appendix, or else omitted completely. 

**4.1 Media**
Remove this section. 

**4.2 Send order**
Rewrite to remove media references. 

**4.4 Decoder**
Rename to "receiver" and make less media dependent. Remove references to frame synchronization. 

**9.2 Object**
Remove reference to payload being a media bitstream. 

**9.3 Catalog**
Catalog definition needs to be written . All the moq-transport spec needs is  normative statement about 1) the reserved naming of the catalog track and 2) that the start of the catalog object payload must hold a cleartext  varint that defines the IANA registered media format type . Everything else about the catalog contents will be defined by the media format spec. 

**10 Setup parameters**
Remove reference to media (replace 'media' with 'content' or 'data')
[
](https://datatracker.ietf.org/doc/draft-law-moq-catalog/)**12 Containers**
Remove this section. It will be defined by media format spec. 

**13.1 Resource exhaustion**
Make media independent

**14 IANA considerations**
moq-transport needs to define a new IANA registry for MOQ Media Formats (name tbd). See https://datatracker.ietf.org/doc/draft-law-moq-catalog/ section 5 for an example. 

**15 Appendix A Video encoding**
Remove this entire appendix.

**16 Appendix B: Object Examples**
Remove. This can be added to the appropriate media format spec.

**Comment by fluffy** [comment]
At a quick skim of above.- looks about right to me. For me, this is all pretty much editorial and sure the editors will do a fine job of it.

**Comment by kixelated** [comment]
How does #150 sound?

**Comment by afrind** [comment]
Did #156 address this issue?

**Comment by afrind** [comment]
This is done.  We probably want an issue to discuss the changes @wilaw wanted to add in #175.
