### ISSUE TITLE
HEADERS encoding

### ISSUE THREAD

**Issue by kixelated** [kixelated/warp-draft#17]
Currently, there's a HEADERS message at the start of each stream, primarily indicating how the stream should be proxied through intermediaries. There's currently no encoding defined and many of the properties are optional.

I see a lot of parallels with HTTP/3. Would it make sense to use HTTP/3? What about just QPACK?

**Comment by afrind** [comment]
Most people hate QPACK.  Maybe re-use the simple encoding from HTTP binary messages: https://www.ietf.org/archive/id/draft-thomson-http-binary-message-00.html


From: kixelated ***@***.***>
Reply-To: kixelated/warp-draft ***@***.***>
Date: Thursday, October 20, 2022 at 5:18 PM
To: kixelated/warp-draft ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [kixelated/warp-draft] HEADERS encoding (Issue #17)

Currently, there's a HEADERS message at the start of each stream, primarily indicating how the stream should be proxied through intermediaries. There's currently no encoding defined and many of the properties are optional. I see a lot of parallels
ZjQcmQRYFpfptBannerStart
This Message Is From an External Sender
ZjQcmQRYFpfptBannerEnd

Currently, there's a HEADERS message at the start of each stream, primarily indicating how the stream should be proxied through intermediaries. There's currently no encoding defined and many of the properties are optional.

I see a lot of parallels with HTTP/3. Would it make sense to use HTTP/3? What about just QPACK?

**Comment by kixelated** [comment]
Yeah that's fair; I've implemented QPACK myself and it's probably too complicated for our use-case.

I think a binary encoding would work best if we are confident about the fields. If there's any ambiguity, then we should use something more dynamic.

**Comment by afrind** [comment]
The HTTP binary encoding for header fields is like

[ Length of Headers ]
([ Length ] [ Header Name String ] [ Length ] [ Header Value String ])+

So it’s just as dynamic as regular HTTP headers.

From: kixelated ***@***.***>
Reply-To: kixelated/warp-draft ***@***.***>
Date: Monday, October 24, 2022 at 10:39 AM
To: kixelated/warp-draft ***@***.***>
Cc: Alan Frindell ***@***.***>, Comment ***@***.***>
Subject: Re: [kixelated/warp-draft] HEADERS encoding (Issue #17)

Yeah that's fair; I've implemented QPACK myself and it's probably too complicated for our use-case. I think a binary encoding would work best if we are confident about the fields. If there's any ambiguity, then we should use something more
ZjQcmQRYFpfptBannerStart
This Message Is From an External Sender
ZjQcmQRYFpfptBannerEnd

Yeah that's fair; I've implemented QPACK myself and it's probably too complicated for our use-case.

I think a binary encoding would work best if we are confident about the fields. If there's any ambiguity, then we should use something more dynamic.

**Comment by kixelated** [comment]
Yeah, I meant that we could also have concrete frame types (ex. PROXY, CACHE?) instead of HEADERS with arbitrary key/value pairs.

**Comment by kixelated** [comment]
Yeah, I meant that we could also have concrete frame types (ex. PROXY, CACHE?) instead of HEADERS with arbitrary key/value pairs.

**Comment by LPardue** [comment]
Not much strong opinion on this. Reusing binary HTTP sounds like a good option, everywhere you can avoid inventing a new things, and worrying about extensibily, increases velocity.

**Comment by fluffy** [comment]
I don't think QPACK buys you much here given the overall usage.

**Comment by kixelated** [comment]
Yeah, I think we should just have a fixed encoding like QUIC/H3 frames.

Originally I was afraid the WG wouldn't buy into the delivery order idea, and everyone would want their own way to decide when to prioritize/drop media. The intent was to use generic key/value pairs so it was extensible.

However the reaction has been far more positive than I expected. For the sake of interop with relays, let's go with a simple and fixed priority scheme. We can decide how extensible it should be with more deployment experience.

**Comment by vasilvv** [comment]
Some issues from discussion on PR #46:

* Do we want to have fixed fields or do we want to have arbitrary key-value pairs?
* If we do, should the keys be numbers or strings?
* If strings, are those ASCII and case-sensitive or not?

**Comment by kixelated** [comment]
This has been rolled into OBJECT
