### ISSUE TITLE
Consider dropping "x-" prefix for custom extensions 

### ISSUE THREAD

**Issue by englishm-ietf** [kixelated/warp-draft#2]
This section:

https://github.com/kixelated/warp-draft/blob/a8e121f901bf0f61a5b59fc56a913688d8b0ecdb/draft-lcurley-warp.md?plain=1#L265-L268

makes a recommendation that appears to be contrary to [RFC6648 - "Deprecating the "X-" Prefix and Similar Constructs in Application Protocols"](https://datatracker.ietf.org/doc/html/rfc6648)

I'd suggest following the recommendations of that RFC and dropping the "x-" prefix for custom extensions.

Additionally, there will probably come a point where IANA registration of standardized extensions may be useful, but it's probably more than a little early to be talking about that.

**Comment by kixelated** [comment]
The new draft doesn't use JSON messages any longer. We'll still want to reserve a number space for custom messages.
