### ISSUE TITLE
Should we specify in-order delivery within segment?

### ISSUE THREAD

**Issue by kpugin** [kixelated/warp-draft#22]
> Note that the contents within each segment are still delivered in order; this delivery order only applies to the ordering between segments.

Are we creating head of line blocking in proxies here? For fmp4 segments without B-frames, we should allow dropping "tail" of the segment.

**Comment by kixelated** [comment]
Yeah, I like the QUIC wording, but we should point out that proxies can introduce latency unless they deliver data out of order.
