### ISSUE TITLE
Discuss possible flow-control deadlocks

### ISSUE THREAD

**Issue by afrind** [kixelated/warp-draft#25]
Any time you have inter-stream dependencies you create the possibility of deadlock if the encoder doesn't ensure that flow control is consumed in dependency order, and/or if the decoder withholds the release of flow control until all dependencies are resolved.  Add some advisory text to this effect.

**Comment by kixelated** [comment]
Hmm, yeah that's unfortunate.

I was thinking there should be an entire section on dependencies, just like there's a section on delivery order. The advisory would make sense in there.
