### ISSUE TITLE
Issues with order

### ISSUE THREAD

**Issue by afrind** [kixelated/warp-draft#27]
> order. An numeric value indicating the delivery order ([Section 3.2](https://kixelated.github.io/warp-draft/draft-lcurley-warp.html#delivery-order)). A sender SHOULD transmit streams with smallest value first, as bandwidth permits. If two streams use the same value, they SHOULD be round-robined. Note that streams can still arrive out of the intended order due to packet loss. This field is optional and the default value is 0.

Can we simply require that order be unique?  I'm thinking that having a sequential queue based on `order` that converts to a round-robin queue when it encounters multiple entries is a pain to implement.

Also, is 0 the right default?  Untagged segments get highest priority?

**Comment by kixelated** [comment]
Yeah, so here's my use-case:

If audio has a smaller order than video, then we could spend all bandwidth downloading 10s of audio and 0s of video. If audio and video have the same order, then we would instead download something like 5s of audio and 2s of video, depending on the relative file size difference.

There's probably a better solution but I want to avoid making prioritization too complex (ex. HTTP/2). It's not too difficult to implement round-robin; basically after sending a stream you keep swapping it with the next stream if they have the same order value.

As for 0 being the default, the intention was to allow negative values. My code uses `-math.MaxInt` for control messages...

**Comment by afrind** [comment]
I think negative values might be bad.  Just reserve 0 for control messages?

I am not a video experience expert, but what happens if the audio and video segments have roughly the same timestamps and the audio stream get higher priority than video?

**Comment by kixelated** [comment]
The production version of Warp uses the sequence number instead of the PTS so they would be equal. This draft doesn't have a concept of sequence numbers since there's no requirement that audio/video segments be aligned.

**Comment by afrind** [comment]
Going to close this out.  There's more work to do with priority and that's reflected in the draft.
