### ISSUE TITLE
IETF115-Handle priority and delivery order 

### ISSUE THREAD

**Issue by suhasHere** [kixelated/warp-draft#36]
From WG discussions, there were few points on separating these concepts and also having a need for relays to just read a single integer (limited in values it can consider) and also pushing complexity to application to control its semantics

We need to discuss further on the next steps here

**Comment by kixelated** [comment]
Personally, I like global integer space (per connection) to specify the transmit order. It adds some complexity for the application to decide how to map media to this single number space, but it makes it easy for relays to transmit in a desired order.

The draft should do a better job indicating that a sender should atempt to transmit in this order, but it can use any prioritization mechanism. The better it can adhere to this order, the better the user experience, but it's not a requirement. This opens the door to using extensisible priorities (ex. limited to 8 urgencies) and/or marking the packets at a lower layer (ex. IP prioritization or lower).

**Comment by fluffy** [comment]
After hearing the discussion in the room, I am pretty sure we should *not* publish the full graph. I had that option in my slides but I don't think we should do that.

**Comment by suhasHere** [comment]
Agree on keeping things simple here by not needing to have the entire graph. Also we need to keep in mind what's the relay/app behavior vs how QUIC stack itself deals with the order. 

Should we have an app level decision to insert/not to insert a given moq object into the quic library
and
Mechanism for QUIC stack to deliver in a given order.

Both of these might be needed for some use-cases. We just need to evaluate a bit more on the scope and impact

**Comment by VMatrix1900** [comment]
This discussion sounds similar to all sorts of priority discussion (see w3c/webtransport#62 and HTTP/2 or HTTP/3 priority. Basically you have a scheduler running on lower layer and an app which only have limited interface to the scheduler. For the scheduler to be useful in real world, app needs to be able to influence its behavior precisely enough by altering the parameter. A general and consist scheduler is hard to design. [RFC 8260](https://www.rfc-editor.org/rfc/rfc8260.html) defines many different scheduler for SCTP which might be useful. However RFC9000 does not describe the scheduler for QUIC. Neither does HTTP/3. We need to evaluate the problem carefully.

**Comment by afrind** [comment]
Can this be collapsed into #139 or is this separate?

**Comment by fluffy** [comment]
Just as a point of note that a good schedule is hard to defines ... I would say a perfect schedule is impossible to define but the whole internet runs fine a good schedulers that are well defined in every router that forms the internet. This problem of fair scheduling is very well understood and it is easy to get a good solution, just impossible to get a perfect solution.

**Comment by afrind** [comment]
The draft has the author's current thinking, with send order and object priority approaches described in the draft.  Can this be closed for now?

**Comment by afrind** [comment]
@suhasHere I'm closing this one out for now, please refer to the two proposals in the draft and open new issues as needed.
