### ISSUE TITLE
Segments vs fragments

### ISSUE THREAD

**Issue by kixelated** [kixelated/warp-draft#49]
I've mentioned this to Suhas a few times but I figured I'd write it down. Here's a breakdown of how CMAF works:

* An **Init Segment** consist of a File Type Box (`ftyp`) and Movie Box (`moov`). The latter contains a description of each track.
* A **Media Segment** consist of a Segment Type Box (`styp`) and any number of **Media Fragments** concatenated.
* A **Media Fragment** consists of a Movie Fragment Box (`moof`) and Movie Data Box (`mdat`). This contains any number of **Samples** for any number of tracks. The `moof` contains the metadata while the `mdat` contains the codec bitstream.
* A **Sample** is a video **Frame** or a group of audio samples (also called a **Frame**), depending on the codec.

So how do we map this to QUIC streams? Currently:

* Warp: each QUIC stream contains a SEGMENT message, with a **Media Segment** , with any number of **Media Fragments**, with any number of **Frames**, until the end of the GoP.
* RUSH: each QUIC stream contains a SEGMENT message with a **Media Segment**, with a single **Media Fragment**, with a single **Frame**.

Does this work or do we shed a layer?

* Warp: each QUIC stream contains any number of FRAGMENT messages, with a single **Media Fragment**, with any number of **Frames**, until the end of the GoP.
* RUSH: each QUIC stream contains a FRAGMENT message, with a single **Media Fragment**.

**Comment by acbegen** [comment]
In CMAF, fragment means independently decodable. Segments may consist of one or more fragments. And you can switch to a different track at a fragment boundary (which also happens to be a segment boundary). Based you wrote above, your definition for a fragment is "looser". I suggest we keep the definitions consistent with CMAF if we will keep it central to MOQ.

**Comment by afrind** [comment]
This issue is pretty old - and the terminology has already changed (possibly more than once) since the last update.  Can we close?
