### ISSUE TITLE
Allow subscribes to request for individual things or group of things

### ISSUE THREAD

**Issue by suhasHere** [kixelated/warp-draft#51]
Based on our brainstorming today, adding a note here.

1. We need a way for a given subscriber to be able to request a group of things that match a certain parts of the Media resource being published to support pushing of those objects as and when they are available
2.  There is also use-cases where an subscriber can ask for a specific object

I think we need to support both ?

**Comment by kixelated** [comment]
The receiver also needs to specify which tracks are supported. For example, there may be 5 renditions ranging from 240p to 1080p, but a device might not support all of them due to the profile, resolution, etc.

**Comment by afrind** [comment]
@suhasHere regarding this

> request a group of things that match a certain parts of the Media resource

Can you give an example of what you are trying to achieve here?

**Comment by afrind** [comment]
Does the current format of SUBSCRIBE_REQUEST with optional Group and Object sequence meet the requirements here?

**Comment by afrind** [comment]
SUBSCRIBE REQUEST now supports requesting entire track, track from starting group, track from starting group/object, and has parameters which can be further use to specify what can be requested.
