### ISSUE TITLE
Something like Manifest

### ISSUE THREAD

**Issue by suhasHere** [kixelated/warp-draft#53]
There are few ideas floating around merging manifest and decoder init info that is cached and can be provided to clients. Also being able to send updated Manifests as needed.

But the goal here is being the realm of manifes-less ( not to require millions of mnifest updates as is done in HLS today)

**Comment by afrind** [comment]
Does PUBLISH_TRACK from #43 meet the need you are describing here?

**Comment by vasilvv** [comment]
@kixelated can this be closed now that CATALOG PR has been merged?

**Comment by kixelated** [comment]
Yeah I think CATALOG meets this requirement, even if there's some noise around the format.
