### ISSUE TITLE
Optimize OBJECT message metadata by requiring Object ID to define delivery order

### ISSUE THREAD

**Issue by wilaw** [kixelated/warp-draft#65]
The Object message contains header info including separate fields for Object ID and Delivery Order. 

```
OBJECT Message {
  Broadcast URI (b)
  Track ID (i),
  Object ID (i),
  Object Delivery Order (i),
  Object Payload (b),
}
```

Given that is in distribution interest to keep this metadata overhead as small as possible, one optimization would be to constrain the Object ID to be a monotonically increasing integer and then remove the Object Delivery Order Field, as the ObjectID could then serve a dual purpose of identifying both the object and its order. new message structure would be:

```
OBJECT Message {
  Broadcast URI (b)
  Track ID (i),
  Object ID (i),
  Object Payload (b),
}
```

Are there any use-cases under which an integer Object ID cannot reasonably be made to work?

**Comment by afrind** [comment]
Object ID needs to be unique but I don't think delivery order does?  

From 5.4 prioritization: 

> If two streams have the same delivery order, they SHOULD receive equal bandwidth (round-robin).

**Comment by wilaw** [comment]
In my reading of 6.2, ObjectID has to be unique within the scope of Broadcast URI + trackID. So you could name the first object in every track "1". 

I was interpreting the order value as the objects order within the track. Since the objects are sent one-per-stream, this allows the receiver to re-order the objects in decode order, since receipt order is not guaranteed between streams. 

Closer reading of 5.4 however indicates that this "order" functions as a priority for transport-level prioritization, not for intra-object re-ordering. In that case it cannot be coupled with the object ID . Closing this tissue.
