### ISSUE TITLE
Relax the CATALOG definition to decouple the base protocol from the streaming format 

### ISSUE THREAD

**Issue by wilaw** [kixelated/warp-draft#66]
The success of HTTP streaming is partly due to the fact that it is built upon ubiquitous low level API, namely HTTP/S GET, POST of binary files.  The distribution architecture (ingest, caching nodes, edge nodes, routers etc) only has to be built to support this API. On top of that can be layered many streaming protocols - such as HLS, Smooth, HDS and DASH. These streaming protocols can innovate and co-exist and also evolve their features without having to make any changes to the distribution network. The distribution network is unaware of the internal workings for the streaming formats. This decoupling allows good economics (any distribution network can deliver any streaming format), scale (because distribution networks are not specific to a streaming format) and innovation ( networks and formats can be improved independently of one another, as long as the both preserve the API interface). 

The current WARP architecture is a relatively tight binding of streaming format to pub/sub architecture, with the CATALOG message having explicit descriptors for a f4mp4 solution with init segments. This is not broad enough to address all the [use-cases](https://datatracker.ietf.org/doc/draft-gruessing-moq-requirements/) that have been defined for MoQ to address.  

One option is to keep adding explicit fields to the CATALOG message as we encounter new use-cases. An alternative approach is that MoQ define a Common Base Protocol of core APIs. These can be very simple constructs such as AUTH,PUBLISH, SUBSCRIBE, ERROR commands and message structure, essentially much of what WARP draft defines. On top of this Base Protocol we can define and operate various streaming formats. Some might use fmp4 only with a 2s delay target, others might focus on real-time communications. But they can coexists and have quite different CATALOG contents. The benefits of economics, scale and flexibility will apply to this MoQ distribution infra as they have applied to HTTP. The WARP draft 03 actually meets many of the requirements for a base protocol definition. 

The primary change that needs to be made is to make the CATALOG message more generic. **The CATALOG message should have a single payload** , rather than a set of fixed fields such as track count, track descriptors, init payload etc. The catalog is a contract between the publisher and the subscriber and defines all the information necessary for the subscriber to subscribe to the broadcast.  At no point should relays have to understand or parse the catalog. It needs to contain a broadcastID and subscribeID(s), but how it does this can be defined differently by formats that extend Common Base Protocol. A simple instantiation of the payload could be a binary encoding of a JSON file. Why text ?- because it's easy for humans to read, manipulate and debug. Don't equate text with the verboseness of HLS playlists. This CATALOG can be intentionally concise and unless the content of the broadcast changes, need only be sent once.

**Comment by suhasHere** [comment]
+1  to Will's comments here. Catalog should be opaque within the media delivery network and can be cached at edges like media objects. In some cases, it is also preferred to encrypt the contents so to avoid metadata leakage while traversing the network

To the extent, Catalogs should be a kind of Media Object and publishers/subscribers can use the same mechanisms for distribting catalogs

**Comment by vasilvv** [comment]
> The current WARP architecture is a relatively tight binding of streaming format to pub/sub architecture, with the CATALOG message having explicit descriptors for a f4mp4 solution with init segments.

fMP4 is one of the formats described, but as far as I am aware, nothing in the spec requires relays to be aware of the format details.

> This is not broad enough to address all the [use-cases](https://datatracker.ietf.org/doc/draft-gruessing-moq-requirements/) that have been defined for MoQ to address.

Could you say more about the specific use cases and the specific problems encountered by those?

> The CATALOG message should have a single payload , rather than a set of fixed fields such as track count, track descriptors, init payload etc. 

I do not believe this is feasible.  The tracks are a protocol-level concept, and any WARP/MoQ implementation has to be aware of different tracks since they are layered onto different QUIC streams.

**Comment by suhasHere** [comment]
> > The current WARP architecture is a relatively tight binding of streaming format to pub/sub architecture, with the CATALOG message having explicit descriptors for a f4mp4 solution with init segments.
> 
> fMP4 is one of the formats described, but as far as I am aware, nothing in the spec requires relays to be aware of the format details.
> 
> > This is not broad enough to address all the [use-cases](https://datatracker.ietf.org/doc/draft-gruessing-moq-requirements/) that have been defined for MoQ to address.
> 
> Could you say more about the specific use cases and the specific problems encountered by those?
> 
> > The CATALOG message should have a single payload , rather than a set of fixed fields such as track count, track descriptors, init payload etc.
> 
> I do not believe this is feasible. The tracks are a protocol-level concept, and any WARP/MoQ implementation has to be aware of different tracks since they are layered onto different QUIC streams.

Yes tracks/streams are protocol level concepts but its for application to define its structure. This specification should mention that a catalog message lists the various resources (Tracks/warpStreams/Representations) but shouldn't define its encoding.

**Comment by wilaw** [comment]
> I do not believe this is feasible. The tracks are a protocol-level concept, and any WARP/MoQ implementation has to be aware of different tracks since they are layered onto different QUIC streams.

In my reading of the current warp-draft, tracks are an application level concept. Warp-draft specifies a protocol for handling the routing of message objects, not of tracks. A sender MUST send each object over a dedicated QUIC stream. Relays see a flow of streams where each stream contains an object. They forward these objects according to the priority defined for each one and to subscribers based upon a match of the BroadcastID and the TrackID. The only components aware that a particular flow of these objects constitute a media track are the publisher and subscriber. The trackID in the message object is a bit of a misnomer - it could be called subscriptionID to better reflect its purpose.

**Comment by gwendalsimon** [comment]
Reading the draft with fresh eyes (sorry if I miss past intense conversations), the idea behind CATALOG (and more generally Warp broadcast) is pretty obscure. Is it an attempt to reproduce (with new terms and concepts) a DASH manifest? 
I can understand why the QUIC underlying protocol and the considered use-cases can require some changes in the definition of media segments, but I am not sure to understand why we would need to change the overall signalling between the client and the server. 
In last year's [DASH-IF exploration group on WebRTC](https://dashif.org/webRTC/report.html), one of the proposals was the integration of session descriptors (related to SDP) into DASH adaptation sets so that we eventually have one common support for discovering the multiple "variants" of a content (being regular DASH segments or WebRTC gateway endpoints). Wouldn't it be possible to do the same with WARP and to describe the Track(s) into an adaptation set?

**Comment by wilaw** [comment]
> Wouldn't it be possible to do the same with WARP and to describe the Track(s) into an adaptation set?

While it is appealing to conceptualize a single document describing the availability of content delivered via HTTP, WebRTC and MoQ, the semantics of  Manifest/AdaptationSet/Representation and the mpd structure was developed by MPEG and is encumbered by their IP rules. I'm not clear enough on IETF IPR policies to know if that is something that could be leveraged directly?

**Comment by wilaw** [comment]
Label for Ted: Architectural

**Comment by VMatrix1900** [comment]
+1 to Will about decoupling the base protocol with the payload codec/format. Relay does not have to be aware of the media payload(it may be encrypted end-to-end anyway). 

Whether the CATALOG contains the track ID and track count depends on what kind of service we want the relay network to provide. If the relay network only provide the object forwarding service, then we do not need to expose the track concept.  If the relay network need to provide track(WarpStream from #69) forwarding service, then the track ID and track count is necessary at least for relay at the edge.

**Comment by kixelated** [comment]
The QUICR architecture is appealing because it's generic. It's a standard pub/sub framework with some different terminology. In RabbitMQ terms it's a topic exchange; messages are routed to queues based on wildcard routing keys.

But first and foremost we're building a live media protocol. I too share the desire to only route objects based on their URI like RabbitMQ, but it gets increasingly difficult to meet all of the live media requirements. I'm afraid that if our primary goal is to develop a generic protocol, then we'll end up with a protocol that does a poor job delivering media while simultaneously being too specialized for other use-cases.

My suggestion is to work backwards. Let's make sure we check all of the boxes first and later figure out if the protocol can be more applicable to other use-cases. I would love to design the next push-based HTTP but it is not the primary goal.

**Comment by kixelated** [comment]
Anyway, about CATALOG in particular:

A broadcast is split into associated tracks. These tracks are presentation timestamp aligned and most critically, share a delivery order space. Broadcast A will not share the same number space as broadcast B.

I'm looking ahead, but I think for features like DVR, prioritization, and server-side ABR need a concept of a broadcast as the largest possible unit. SUBSCRIBE is scoped to a broadcast for that reason.

But 100% we don't want the relay having access to anything it doesn't need. The idea behind the container formats is that it's an opaque blob to the relay; it SHOULD NOT parse the contents. But I still think the relay needs to know which objects are part of which track and broadcast.

**Comment by kixelated** [comment]
I think this issue could be best summarized as "does the relay need to know about the broadcast/track/object hierarchy?" 

If no, then I like the QUICR design. The endpoints exchange some blob and instruct the relay to push objects according to some rules.
If yes, then we need separate broadcast/track/object IDs. The CATALOG message would provide any additional information needed by the relay, such as the timestamp/order space.
If maybe, then start by assuming "yes" and reevaluate if we can say "no" in the future.

**Comment by wilaw** [comment]
Here's what I propose based on the interim discussion

```
CATALOG Message {
  Broadcast URI (b),
  Format (i),
  Payload (b)
}
```

where

- Broadcast URI: The broadcast URI defining the session
- Format (i): a registered identifier for the format of the payload i.e 1 = WARP, 2 = QUICR, 3 = VR-Special
- Payload: a binary object that can be parsed by any client understanding the format. This payload MUST describe the subscription IDs that the client will use to request content. It may define tracks,  selection criteria for those tracks, along with initialization and other useful information for the client. The payload is not intended to be read by relays and may be encrypted for privacy.

**Comment by kixelated** [comment]
Martin brought up a good point in chat. If a relay doesn't know the valid track IDs, then it will have to forward every SUBSCRIBE to the origin. This could be an abuse vector although I suppose it's no different than HTTP.

**Comment by wilaw** [comment]
The relay does not need to know the trackIDs, as it receives them in the SUBSCRIBE request from the client. The relay has to forward just one subscribe request to the origin, as that is the only way for it to receive the content. Once it has made that one subscribe request for that trackID, any new requests for subscription it can be satisfied from its cache. This is similar to how hierarchical HTTP caching works. 

The only case is which the relay would have to forward each SUBSCRIBE request to the origin is if the system implemented origin-based AUTH and wanted to authorize each subscribe request in the centralized origin.  That has clear scalability problems and I'd not recommend that we do it. The solution is to delegate auth to the edge relays by way of tokens/certs , which again is what we do with HTTP delivery.

Regarding abuse, yes, in an open network you do not know if each incoming request is valid or malicious. Today you can ask any CDN server for anything, and it will do a bunch of work trying to find that content for you. This is an attack vector and CDNs as a consequence get DOS'd every day. But they are designed for that and so would our hypothetical MoQ CDN. You can reduce most malicious or fake requests at the edge by requiring some form of authentication to accompany the request. By requiring AUTH on the original webtransport connection, we could better trust subscribe requests that occur within it.

**Comment by afrind** [comment]
It sounds like doing this would also make CATALOG messages entirely optional in the base protocol spec, as that same information could be exchanged out of band.  I do like having an in-band mechanism even if it's somewhat generic (at the base level)

**Comment by wilaw** [comment]
IMO the CATALOG message and its response should exist in the base protocol and be mandatory to implement on the part of the publisher and relays. For the client, its optional. The majority of clients would use it. Those that can receive the catalog out-of-band would not need to use it. I envisage CATALOGS not being static in the life of a stream. They should update when the mix of content being produced by the publisher changes (i.e a webex user suddenly starts sharing their desktop). To that end, even a client that starts with an out-of-band catalog would still want to SUBSCRIBE to CATALOG updates, so that it can be apprised of any future changes to the subscription IDs on offer. I can also imagine dynamic ad insertion opportunities being signaled by CATALOG changes. Additionally, a CATALOG update to say there is no more content being published would be a clean way to terminate a broadcast.

**Comment by afrind** [comment]
Speaking as an individual.

So to clarify you mean publishers MUST publish a CATALOG?  Is it ok to define a catalog that is just a URL (pointer to the real catalog)?

If the catalog is more dynamic, we may want more than just a single "CATALOG - here it is" kind of message, to help endpoints from having to compare two catalogs and try to figure out what changed.  Or maybe an operation type in the message like "append (add these catalog contents to the previous one), remove (subtract these catalog elements), update (update these catalog elements, leaving the rest unchanged), replace (this is a totally new catalog)".  My understanding of manifest files is that their lack of append-ability is a major pain point.  I guess if a relay never looks at catalog contents, only append and replace are easily implementable.

**Comment by wilaw** [comment]
> So to clarify you mean publishers MUST publish a CATALOG? 

Yes. A publisher MUST create a CATALOG to describe the media tracks that they are producing.

>  Is it ok to define a catalog that is just a URL (pointer to the real catalog)?

I guess we could allow that. However it seems a bit strange that we would use an out-of-band mechanism to describe something so central to MoQ as the CATALOG, which is the contract between publisher and subscriber. To enable fast start for clients, the publisher could supply the CATALOG in-band but then also supply it to a 3rd party CMS service which gave it to the client. This would allow the client to know the subscription IDs before joining via MoQ, which would allow it to append them to the CONNECT or SETUP and thereby have the relay immediately start to forward the media, reducing the start time by 1xRTT.

> If the catalog is more dynamic, we may want more than just a single "CATALOG - here it is" kind of message, to help endpoints from having to compare two catalogs and try to figure out what changed.

Yes, this is efficient if the CATALOG is a verbose object and if we can guarantee that subscribers see the full sequence of updates and hence can build up the final model by compositing the delta updates (or patches if its easier to think of them that way). Two problems with this that would need addressing: 1) New subscribers joining late. We would have to teach the relay to cache all old CATALOG messages, including the original and every patch, and then send them to the new subscriber in the correct order when asked to supply the CATALOG. 2) Accrued updates - over a long running web conference among a hundred interactive users, there could be hundreds of CATALOG updates. For late joining clients, these would all need to be sent in the correct order. 

 If the CATALOG can me made concise, then having it hold the absolute independent state (versus a relative dependent one) and having the client figure out the difference makes relay forwarding and client joining simpler. I could see allowing both modes and letting implementers choose based upon the anticipated size of their CATALOGS, the rate of change and the duration of the broadcast. My preference would be that we keep the CATALOG as small as possible, that it provide only the current state, and that the clients figure out the difference.

**Comment by VMatrix1900** [comment]
Can we treat the CATALOG like the video stream? Priodically sync the full CATALOG(snapshot), delta update in between. Just like the I frame and P frame. In this way, the data model of the CATALOG and the media can be unified.

**Comment by VMatrix1900** [comment]
Using the term defined in #69, The MoQ media session would be composed by one CATALOG stream + multiple Media streams. Both CATALOG stream and media stream includes group of objects. For video media stream, the object can be frame/slice/GoP. For CATALOG stream, the object can be SETUP message, Paticipant JOIN/LEAVE message, Media JOIN/LEAVE message. SETUP message is a full snapshot of the CATALOG while other message can change the CATALOG.

**Comment by suhasHere** [comment]
Consider catalog as another form of track is cleaner in the design. Like objects from a media track are indistinguishable from blob of catalog for the relays, having its own message type for catalog seems unnecessary, I feel.

Clients get list of media tracks from Catalog and they can get catalog trackId as well. Clients would know how to parse these.

**Comment by wilaw** [comment]
@VMatrix1900  - I like the conceptual idea that the Catalog as a type of media stream, with independently decodable points and then deltas in between. There is a nice symmetry there with media. We can debate whether participants joining/leaving should be a separate message type, or just a delta update to the catalog object reflecting the change in available participants. Notions like "participants" and "join/leave" are very specific to web conferences and have little correlation if the broadcast represents a sports game. If we are to satisfy multiple use-cases with MoQ (as per our charter), then I feel that for MoQ Base protocol we should generalize the CATALOG as some object that has either an  independent state or a dependent state. Per #85, the contents of the catalog can be specified by a separate spec, which for a web conference would define semantics around join/leave and for a sports game might instead describe different camera views, drone footage etc. If we give each CATALOG object a sequence identifier, then we can signal dependency by simply referring to a prior object sequence identifier. 


```
CATALOG Message {
  Broadcast URI (b),
  Format (i),
  Sequence (i),
  Dependency (i),
  Payload (b)
}
```

where

- Broadcast URI: The broadcast URI defining the session
- Format (i): a registered identifier for the format of the payload i.e WARP = 1, QUICR = 2
- Sequence (i): an integer that starts at 1 and increases sequentially at the original media publisher. Sequences are scoped to the BroadcastURI.
- Dependency (i): an integer that specifies a prior sequence number on which this message depends. A dependency of 0 signals an independent message. 
- Payload: a binary object that can be parsed by any client understanding the format. This payload MUST describe the subscription IDs that the client will use to request content. It may define tracks, selection criteria for those tracks, along with initialization and other useful information for the client. The payload is not intended to be read by relays and may be encrypted for privacy.

**Comment by VMatrix1900** [comment]
> Dependency (i): an integer that specifies a prior sequence number on which this message depends. A dependency of 0 signals an independent message.

Will a CATALOG object depends on multiple previous objects? Just like a B frame can improve the compression efficiency,  allowing multiple dependency may improve the CATALOG update speed.

**Comment by wilaw** [comment]
> Will a CATALOG object depends on multiple previous objects?

I think that's unnecessary complexity. We're not encoding macro-blocks here, we're just communicating the availability of subscribable tracks for a broadcast.  Can you describe a use-case which warrants a multi-parent dependency tree for the CATALOG description?

**Comment by wilaw** [comment]
@vasilvv  - can you look over this issue, particularly the proposal of https://github.com/kixelated/warp-draft/issues/66#issuecomment-1442481197. We are both assigned to resolve. I'd like to prepare a PR for the  interim meeting next week and will do so, but would prefer your consensus or opinion before doing that.

**Comment by vasilvv** [comment]
I don't think I fully understand the idea proposed in that comment.

(1) If catalog is a type of the track, how would a player identify which track is the catalog without prior knowledge?
(2) If catalog is a type of the track, why do we need a separate catalog message in the protocol?

**Comment by VMatrix1900** [comment]
@vasilvv I think your second question answers the first one. We need a separate catalog message to distinguish from the object message.

**Comment by wilaw** [comment]
>  If catalog is a type of the track, how would a player identify which track is the catalog without prior knowledge?

One way is for the spec to define a reserved trackID that would always represent the catalog. For example , a trackID of 0. 

> If catalog is a type of the track, why do we need a separate catalog message in the protocol?

If we want to use the existing OBJECT message to carry catalog information, and we allow that catalog payload to vary with application, then we would need to take one of these actions:

- add a field to the OBJECT message indicate the type of catalog that might be carried. This field would be wasted overhead for all audio/video (non-catalog) messages.
- we could define that the catalog payload MUST start with a standard header which defines the type. This limits the binary packing options which different formats may want to explore for their catalogs.
- we could define a new OBJECT ID for each catalog type. For example, current draft specifies just one catalog type of 0x2. However we could define 0x2 = WARP catalog, 0x3 = QUICR, OxN = something else. 
- or we keep the separate CATALOG message and adjust its fields as suggested

**Comment by vasilvv** [comment]
The more I think about it, the more I like the idea of catalog as its own track.  We had an issue figuring out how to update the catalog before; if we make it its own track, it will become a subject to the timing model of the broadcast, which should help with updating it.

> One way is for the spec to define a reserved trackID that would always represent the catalog. For example , a trackID of 0.

I like that idea.

> add a field to the OBJECT message indicate the type of catalog that might be carried. This field would be wasted overhead for all audio/video (non-catalog) messages.

I agree that adding a field for this sole purpose seems wasteful.  I suspect that down the line we might find ourselves having to add more optional fields to the OBJECT message, and this would fit in nicely, but right now that is not the case.

> we could define that the catalog payload MUST start with a standard header which defines the type. This limits the binary packing options which different formats may want to explore for their catalogs.

I think this is the best answer.  Could you explain how this limits the packing options?  I assume you would just parse the header and then whatever comes after the header is entirely up to the application.

> we could define a new OBJECT ID for each catalog type. For example, current draft specifies just one catalog type of 0x2. However we could define 0x2 = WARP catalog, 0x3 = QUICR, OxN = something else.

> or we keep the separate CATALOG message and adjust its fields as suggested

I feel like not using the OBJECT message kind of defeats the purpose of making catalog be a form of track data.

**Comment by VMatrix1900** [comment]
> We had an issue figuring out how to update the catalog before; if we make it its own track, it will become a subject to the timing model of the broadcast, which should help with updating it.

Exactly. The catalog shares the timing model with the object message. 

However, the CATALOG as a track does not mean that the OBJECT message shares the same header fields with the OBJECT message. For example, the object delivery order field may only apply to the Object message and the CATALOG message is always the highest priority. 

> - add a field to the OBJECT message indicate the type of catalog that might be carried. This field would be wasted overhead for all audio/video (non-catalog) messages.
> - we could define that the catalog payload MUST start with a standard header which defines the type. This limits the binary packing options which different formats may want to explore for their catalogs.
> - we could define a new OBJECT ID for each catalog type. For example, current draft specifies just one catalog type of 0x2. However we could define 0x2 = WARP catalog, 0x3 = QUICR, OxN = something else.
> - or we keep the separate CATALOG message and adjust its fields as suggested

Basically, above options are about which field to put the type number for CATALOG. I would add another option: use the delivery order 0(highest) to indicate that OBJECT is the CATALOG message.

I suggest we figure out the format of CATALOG message and OBJECT message separately, then consider if/how to merge them.

**Comment by wilaw** [comment]
> Could you explain how this limits the packing options? I assume you would just parse the header and then whatever comes after the header is entirely up to the application.

Assume there are two parallel catalog formats A and B. A chooses to define its catalog using Protobuf, while B uses MessagePack. Each would have a different way to serialize "type=1". So my initial thought is that if we prescribe one way of doing it, then we force format architects to use that serialization in their catalogs. However upon further thought, we can just define that the first N bytes of the catalog payload define the catalog type and then after that the catalog-specific serialization kicks-in. So I'm fine with this solution to the problem of identifying the catalog type. 

> For example, the object delivery order field may only apply to the Object message and the CATALOG message is always the highest priority.

I think catalog-as-object and media-as-object could share the same priority scheme. If someone always want the catalog updates sent ahead of the media, then they can give them a higher priority. We should not force catalog objects to be the highest priority, there may be some future application which does not want that behavior. 

> I would add another option: use the delivery order 0(highest) to indicate that OBJECT is the CATALOG message.

I think that overloading the priority field for catalog ID type would work us in to a corner pretty quickly. 

> I suggest we figure out the format of CATALOG message and OBJECT message separately, then consider if/how to merge them.

Catalog can fit quite neatly into the Object scheme. Here's what a catalog object would look like, assuming the Group and Object sequence counters can be used to describe any dependency:


```
OBJECT Message {
  Broadcast URI (b)
  0,
  Group Sequence (i),
  Object Sequence (i),
  Object Delivery Order (i),
  Object Payload (b),
}
```

where 

```
Payload {
    type (i)
    catalog (b)
}
```

**Comment by vasilvv** [comment]
So it sounds like instead of using the CATALOG message, we can define that
1. Track 0 is always the catalog.
2. Every object in the catalog starts with a header (varint62?) that tells you what is the format of the catalog used.
3. The rest of the object contents is interpreted according to the format corresponding to the varint.

Does this sound reasonable?

**Comment by wilaw** [comment]
Yes. I would adjust items [2] and [3] to use the language of the OBJECT message:

- Track 0 is always the catalog.
- The payload of every OBJECT message with a trackID of 0 starts with a header (varint62?) that tells you what is the format of the catalog used.
- The remainder of the OBJECT payload is interpreted according to the format corresponding to the varint.

We should also figure out how to signal the dependency issue raised earlier in the thread. The use case is a larger initial catalog of many subscribable items with later updates where just a few of those items change. For efficiency we'd like to distribute just the updates to subscribed clients. New clients joining however will need to start at an independent point.  For this I propose that we leverage the Group sequence (of the OBJECT message) to indicate an _independent_ catalog and the object sequence to indicate a _dependent_ one.

```
Group 0
     Object 0
     Object 1
     Object 2
Group 1
     Object 0
     Object 1
```

A client already subscribed to track 0 would receive [1,1] and be able to update its model of the catalog.
A new client joining would have to be sent [1,0] and [1,1] in order to have an up-to-date view of the catalog. The relay would know what to send because it could look in its cache for the highest Group sequence for track 0 and send from that point on. 
A broadcast in which nothing changes would send [0,0] for track 0 and be done. 
[N,0] are independent catalog payloads sent by the publisher at some interval, much like I-frames in a encoded video sequence.

**Comment by kixelated** [comment]
Shoving CATALOG inside of an OBJECT payload makes sense. You could even use the same encoding if you wanted. Using track 0 as the CATALOG track seems cool.

I'm not sure I follow the independent versus dependent catalog stuff. It sounds like the goal is to reduce the scope of catalog updates. When broadcaster Z publishes a new track, you don't want to send the CATALOG for track A-Y since they didn't change. As a relay I would rather not keep a chain of every TRACK update, replaying them when a new viewer joins.

What if we had a separate TRACK_CATALOGs? Most of the information in the CATALOG is specific to a single track anyway, with only a handful of fields to unite them. There's no reason to retransmit everything when on a single track is added/removed/updated.

What if OBJECT 0 for each track is the TRACK_CATALOG? A publisher would send OBJECT 0 for every track on a new connection. The subscriber would issue a SUBSCRIBE if it wants more of the track. A new track being added to a broadcast would 

What if TRACK_CATALOG... was just an init segment! Each track would start with an init segment, which is super clean.

I think we still need CATALOG, but it can be extremely minimal. Just a list of active track IDs and some relationship between them. Then there's no need for deltas any longer.

**Comment by VMatrix1900** [comment]
> We should also figure out how to signal the dependency issue raised earlier in the thread. The use case is a larger initial catalog of many subscribable items with later updates where just a few of those items change. For efficiency we'd like to distribute just the updates to subscribed clients. New clients joining however will need to start at an independent point. For this I propose that we leverage the Group sequence (of the OBJECT message) to indicate an independent catalog and the object sequence to indicate a dependent one.

Can we reuse the dependency for OBJECTS? For example, an OBJECT depends on prior OBJECTS within the same group. The first OBJECT of the group is a full set of the track IDs, each following OBJECT is the delta update of the set. Kind of like the I frame and P frame.

**Comment by afrind** [comment]
@wilaw : given that the CATALOG message and media references has been removed from the draft, are we good to close this one?  See #156.

**Comment by wilaw** [comment]
Yes. Closing. I'll open a new issue about catalog requirements for moqt.
