### ISSUE TITLE
Data Model needs to expand to support different use-cases

### ISSUE THREAD

**Issue by suhasHere** [kixelated/warp-draft#68]
The currently proposed data model in -03 is a good start, but it does seem to lack things needed to various use-cases as defined in (https://datatracker.ietf.org/wg/moq/about/)

  -  querying/subscribing to data from Relay at various granularities in a application agnostic way 
  -  represent different forms of  media objects grouping - gops, slices,  audio groups, something new
  -   describe dependencies between objects within a group enabling relays appropriate caching strategies.

**Comment by vr000m** [comment]
Does this issue also cover one publisher per broadcast or is that another issue?

**Comment by afrind** [comment]
Does the now-merged model of track/group/object resolve this issue?

**Comment by afrind** [comment]
Data model has been updated
