### ISSUE TITLE
"fully supports ECN"

### ISSUE THREAD

**Issue by martinduke** [kixelated/warp-draft#77]
Sec 5.7. "It is NOT RECOMMENDED to use a loss-based algorithm (ex. [[NewReno](https://kixelated.github.io/warp-draft/draft-lcurley-warp.html#NewReno)]) unless the network fully supports ECN."

1) Thanks for mentioning ECN!

2) Add a reference! Do you mean RFC 3168, RFC 9330 (L4S), or both? I'm not sure 3168 helps all that much with bufferbloat, but regardless the draft should say what you mean.

3) What is "full support" for ECN and how would an endpoint know this? Perhaps you mean "all routers in the path apply congestion markings in accordance with the scheme we operating" and an endpoint knows this a priori (perhaps because it's a transfer to a relay over a single AS). But the draft should be more specific!

**Comment by fluffy** [comment]
I think things about congestion control algorithms are probably best left to the QUIC layer than trying to deal with them at MoQ layer.

**Comment by afrind** [comment]
This section (and the ECN reference) got removed in the latest draft.  @martinduke Is it OK to close this issue?

**Comment by martinduke** [comment]
SGTM
