### ISSUE TITLE
Broadcast URI in Object message

### ISSUE THREAD

**Issue by kpugin** [kixelated/warp-draft#82]
Currently Object message specify Broadcast URI for every object - that's going to be pretty big overhead, especially for low bitrate videos and audio. This one of the current problems for example with fMP4 and according to some analysis overhead just from 1 frame CMAF chunks can be 10+ %

**Comment by grmocg** [comment]
Two concerns to address:
1- how to address this thing without too much waste on the wire
2- how to consistently address this thing such that we don't waste lots of space in memory and also waste compute remapping things in relays.

**Comment by fluffy** [comment]
Given this never changes for the track, I don't see why every audio packet would need a URI. It also seems for the level of where MoQ works and the different applications, a track URI is more what we want than the broadcast, of course the application may have a concept of broadcast, but it seems at the MoQ layer is more working at the track level.

**Comment by kixelated** [comment]
This has been addressed in #98. The URL in the WebTransport CONNECT is used to identify the track bundle (aka broadcast) and all tracks/objects are scoped to it. Effectively it's a lookup table now based on the WebTransport session.

There's an open discussion how the Track ID is scoped. I think it should be relative to the track bundle, but I've heard a few options that it should be global or even scoped to the CDN. The bigger the scope, the more bytes you need for the ID, and the more bytes for each OBJECT.

**Comment by fluffy** [comment]
can we close this ?

**Comment by afrind** [comment]
> can we close this ?

+1 

@kpugin are you good here?

**Comment by afrind** [comment]
OBJECT message now contains a "track id" varint rather than the full URL
