### ISSUE TITLE
Move Catalog details to its own spec

### ISSUE THREAD

**Issue by suhasHere** [kixelated/warp-draft#85]
Today the protocol specifies the format of the catalog message. Should we keep it opaque and have an extension spec to define container specific catalog formats

**Comment by vasilvv** [comment]
If we remove CATALOG, how would we deal with INIT segments?

**Comment by kixelated** [comment]
INIT segments could be in the catalog itself, kind of like how you can base64 them in DASH.

**Comment by afrind** [comment]
Is this a duplicate of #66?

**Comment by suhasHere** [comment]
Agree with @kixelated .. If the container type is CMAF, the init segment is part of Catalog for a given track. This issue is proposing moving format specific catalog definition to companion spec IIUC from the discussions

**Comment by afrind** [comment]
Is this a duplicate of #66
