### ISSUE TITLE
Scalable Video Coding

### ISSUE THREAD

**Issue by kixelated** [kixelated/warp-draft#9]
The current draft assumes that media segments are independent. However, scalable video coding (SVC) exists and is likely something we should support in the future. I don't have any experience with SVC but AFAIK, you could have a 720p rendition that depends on a 360p rendition, so they can share some compression.

My idea was to support it by indicating that segments can reference other segments. The decoder would know that SVC is being used and that it needs to interleave segments from multiple streams. Or is this something we should indicate at the track/rendition level instead of the segment level? Or is this something we don't need to support at the Warp level at all?

**Comment by VMatrix1900** [comment]
Instead of one-dimensional frames dependency in which a frame only depends on its adjacent frame(s), SVC encoder produces frames of multiple layers in which higher-layer frames usually depend on lower-layer ones. This will produce multiple layers of segments in Warp's term. Knowing the dependency between segments can help Warp to make better scheduling decision.

**Comment by acbegen** [comment]
I would not really bother with scalable video codecs until more important issues are addressed (for example allowing for rate shifting across normal (non-scalable) encodings). Scalable codecs don't allow arbitrarily jumping from one resolution to another. There are significant limitations on what you can do. In addition to in-segment dependencies, you will create across-segment dependencies which will make things like prioritization even more complicated. Also to get the same quality with a codec like SVC, you always need to download more bits compared to AVC or alike. For your primary use case which is 1:1 media, I don't see any benefit here.

**Comment by kixelated** [comment]
Yeah, Warp is simple because a stream == GoP. It gets more complicated when you try to break a GoP into smaller pieces that depend on each other.

**Comment by kixelated** [comment]
The new draft breaks streams into layers, including SVC layers. I could use some SVC expert to chime in on what else is needed but this is supported (at least in spirit) now.
